<div id='buttonPanel' class='interfacePanel'/>
<div id='buttonVPanel' class='interfacePanel'/>
<div id='sliderPanel' class='interfacePanel'/>
<div id='xyPanel' class='interfacePanel'/>
<div id='knobPanel' class='interfacePanel'/>
<div id='crossfaderPanel' class='interfacePanel'/>
<div id='rangePanel' class='interfacePanel'/>
<div id='multiSliderPanel' class='interfacePanel'/>
<div id='multiButtonPanel' class='interfacePanel'/>
<div id='pianoPanel' class='interfacePanel'/>
<div id='textFieldPanel' class='interfacePanel'/>
<div id='menuPanel' class='interfacePanel'/>
<div id='labelPanel' class='interfacePanel'/>